#!/bin/bash
#SBATCH -c 1
#SBATCH -t 0-00:10
#SBATCH -p short
#SBATCH --mem=2G
#SBATCH -o run_PHESANT.out
#SBATCH -e run_PHESANT.err


# runs PHESANT on exposures table generated by 'extract_pheno.R'

#cd ~/PHESANT/WAS/
dir_PHESANT_WAS="~/PHESANT/WAS/"

Rscript ${dir_PHESANT_WAS}phenomeScan.r \
--phenofile="/home/nur479/scratch3/PXS_pipeline/T2D_exposures_tbl_raw.txt" \
--variablelistfile="${dir_PHESANT_WAS}../variable-info/outcome-info.tsv" \
--datacodingfile="${dir_PHESANT_WAS}../variable-info/data-coding-ordinal-info.txt" \
--resDir="~/scratch3/PXS_pipeline/PHESANT_results/" \
--genetic=FALSE \
--save \
--tab=TRUE